"""Where Kuwagata's offsets live in the other release.

Medarot Navi shipped twice on the same day — Kuwagata and Kabuto — and the two
cartridges are the same build with the data shifted: the fonts, the scripts,
the graphics and the tables are byte-identical, they simply sit a few hundred
bytes apart. Everything this project knows about the game is written down as a
Kuwagata offset, in the module that uses it, and re-deriving all of it by hand
for the second release would be the same reverse-engineering work twice.

So it is derived once, mechanically. This module aligns the two dumps into a
list of ``(kuwagata, kabuto, length)`` runs and answers one question:

    >>> align.at(0x658BF0)      # the dialogue font, in Kabuto
    0x657D60

The map is generated by ``tools/align.py`` from two dumps and committed as
``data/offsets-kabuto.json`` — offsets and lengths only, never bytes, so the
repository still carries nothing of the game. A lookup that lands outside every
run returns ``None`` and the caller leaves that asset alone: an address this
map cannot vouch for is one where the two releases genuinely differ (the title
screen's cover Medabot, the eleven scripts that name it), and writing there
blind is how a build corrupts a sprite nobody looks at until hours in.
"""

from __future__ import annotations

import json
from bisect import bisect_right
from dataclasses import dataclass
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent.parent / "data"

#: Bytes that have to agree before a stretch counts as the same data.
MIN_RUN = 24

#: How far apart the two releases' copies of one thing may sit.
SEARCH = 0x80000

#: Bytes of a sample window, and how often to take one while hunting shifts.
SAMPLE = 48
SAMPLE_STEP = 0x800


@dataclass(frozen=True)
class Alignment:
    """One release's offsets, expressed in another's."""

    source: str
    target: str
    runs: tuple[tuple[int, int, int], ...]

    def __post_init__(self) -> None:
        object.__setattr__(self, "_starts", [run[0] for run in self.runs])

    def at(self, offset: int, length: int = 1) -> int | None:
        """Where ``offset`` is in the target release, or None if unknown.

        ``length`` asks for the whole span to be inside one run: a table that
        straddles the seam between two runs is not the same table twice.
        """
        starts = getattr(self, "_starts")
        index = bisect_right(starts, offset) - 1
        if index < 0:
            return None
        start, target, size = self.runs[index]
        if offset + length > start + size:
            return None
        return target + (offset - start)

    def back(self, offset: int, length: int = 1) -> int | None:
        """The reverse: a target offset expressed in the source release."""
        by_target = getattr(self, "_by_target", None)
        if by_target is None:
            by_target = sorted(self.runs, key=lambda run: run[1])
            object.__setattr__(self, "_by_target", by_target)
            object.__setattr__(self, "_target_starts",
                               [run[1] for run in by_target])
        starts = getattr(self, "_target_starts")
        index = bisect_right(starts, offset) - 1
        if index < 0:
            return None
        source, start, size = by_target[index]
        if offset + length > start + size:
            return None
        return source + (offset - start)

    def near(self, offset: int, slack: int = 0x1000) -> int | None:
        """Where a BOUNDARY lands, extrapolated from the data before it.

        A region's end is not data and often falls in a gap between two runs.
        Walking back to the last byte the two releases agree on and adding the
        distance again puts the boundary at the same place relative to the
        data it closes — which is all a scan needs from it. Never use this for
        an address something is written to: :meth:`at` says None there for a
        reason.
        """
        for back in range(slack):
            where = self.at(offset - back)
            if where is not None:
                return where + back
        return None

    def covered(self) -> int:
        return sum(size for _, _, size in self.runs)


IDENTITY = Alignment(source="", target="", runs=())
"""The alignment a release has with itself: every offset is where it says."""


# The empty run list would answer None to everything; a release aligned with
# itself has to answer the offset it was given.
object.__setattr__(IDENTITY, "at", lambda offset, length=1: offset)
object.__setattr__(IDENTITY, "back", lambda offset, length=1: offset)
object.__setattr__(IDENTITY, "near", lambda offset, slack=0x1000: offset)


# -- loading -------------------------------------------------------------


_CACHE: dict[str, Alignment | None] = {}


def load(target: str) -> Alignment | None:
    """The committed map from Kuwagata to ``target``, if there is one."""
    key = target.lower()
    if key in _CACHE:
        return _CACHE[key]
    path = DATA_DIR / f"offsets-{key}.json"
    alignment = None
    if path.is_file():
        raw = json.loads(path.read_text(encoding="utf-8"))
        # The pointer tables are listed apart because they were found by what
        # they point at rather than by their bytes; for a lookup they are runs
        # like any other, and they sit in the holes between the content ones.
        runs = [tuple(run) for run in raw["runs"]]
        runs += [tuple(run) for run in raw.get("tables", {}).values()]
        runs.sort()
        alignment = Alignment(
            source=raw.get("from", "Kuwagata"),
            target=raw.get("to", target),
            runs=tuple(runs),
        )
    _CACHE[key] = alignment
    return alignment


def for_release(name: str) -> Alignment:
    """The alignment to use for a release, identity for the canonical one."""
    if name.lower() == "kuwagata":
        return IDENTITY
    alignment = load(name)
    if alignment is None:
        raise FileNotFoundError(
            f"No offset map for {name}: run tools/align.py with both dumps")
    return alignment


# -- deriving ------------------------------------------------------------


def _shifts(a: bytes, b: bytes) -> list[int]:
    """Every distance the data seems to have moved by, most common first.

    Sampling rather than searching: the releases shift whole regions, so a
    window taken every few kilobytes finds each region's shift many times over,
    and a shift that only one sample ever sees is not a region.
    """
    counts: dict[int, int] = {}
    for at in range(0, len(a) - SAMPLE, SAMPLE_STEP):
        window = a[at:at + SAMPLE]
        if len(set(window)) < 4:
            continue        # padding and blank tiles match everywhere
        found = b.find(window, max(0, at - SEARCH), min(len(b), at + SEARCH))
        if found < 0:
            continue
        counts[found - at] = counts.get(found - at, 0) + 1
    return [delta for delta, _ in sorted(counts.items(), key=lambda kv: -kv[1])]


def _runs_at(a: bytes, b: bytes, delta: int) -> list[tuple[int, int]]:
    """Stretches of at least MIN_RUN bytes that agree at this shift.

    XORing the two ROMs as one big integer is the whole trick: it is a single
    C-level operation over eight megabytes, and every zero byte of the result
    is a byte the two releases agree on. Comparing byte by byte in Python takes
    minutes; this takes milliseconds.
    """
    lo = max(0, -delta)
    hi = min(len(a), len(b) - delta)
    if hi - lo < MIN_RUN:
        return []
    size = hi - lo
    left = int.from_bytes(a[lo:hi], "big")
    right = int.from_bytes(b[lo + delta:hi + delta], "big")
    mask = (left ^ right).to_bytes(size, "big")

    out: list[tuple[int, int]] = []
    needle = bytes(MIN_RUN)
    at = mask.find(needle)
    while at >= 0:
        end = at + MIN_RUN
        while end < size and mask[end] == 0:
            end += 1
        out.append((lo + at, end - at))
        at = mask.find(needle, end)
    return out


def compute(a: bytes, b: bytes, source: str = "Kuwagata",
            target: str = "Kabuto") -> Alignment:
    """Align two dumps into non-overlapping runs, longest match winning."""
    candidates: list[tuple[int, int, int]] = []
    for delta in _shifts(a, b):
        for start, length in _runs_at(a, b, delta):
            candidates.append((start, length, delta))
    candidates.sort()

    starts = [item[0] for item in candidates]
    runs: list[tuple[int, int, int]] = []
    at = 0
    index = 0
    reach: list[tuple[int, int, int]] = []
    while at < len(a):
        while index < len(candidates) and candidates[index][0] <= at:
            reach.append(candidates[index])
            index += 1
        # of everything that covers this byte, take the one reaching furthest
        best = None
        for start, length, delta in reach:
            if start + length <= at:
                continue
            if best is None or start + length > best[0] + best[1]:
                best = (start, length, delta)
        if best is None:
            nxt = bisect_right(starts, at)
            if nxt >= len(candidates):
                break
            at = candidates[nxt][0]
            reach = []
            continue
        start, length, delta = best
        end = start + length
        if runs and runs[-1][1] + runs[-1][2] == at + delta and \
                runs[-1][0] + runs[-1][2] == at:
            # same shift, no gap: one run
            runs[-1] = (runs[-1][0], runs[-1][1], runs[-1][2] + end - at)
        else:
            runs.append((at, at + delta, end - at))
        at = end
        reach = [item for item in reach if item[0] + item[1] > at]
    return Alignment(source=source, target=target, runs=tuple(runs))
