"""Derive data/offsets-<release>.json from two dumps.

    python3 tools/align.py "Medarot Navi - Kabuto (Japan).gba"

Reads the ROM the tools are pointed at (`navi.py rom`) as the source — it must
be the Kuwagata release, which is the one every offset in this project is
written against — aligns the second dump with it, and writes the run map.
Offsets and lengths only: no byte of either cartridge enters the repository.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from navi import align
from navi.config import Config
from navi.rom import Rom

#: Things whose Kuwagata offset is known, and where each one must land.
ANCHORS = (
    ("dialogue font", 0x658BF0),
    ("kanji font", 0x6593D0),
    ("1bpp-to-4bpp table", 0x4C75E8),
    ("team info table", 0x86640),
)

#: Tables of POINTERS, which no content match can ever find: every word in
#: them names an address, and the addresses are exactly what the two releases
#: disagree about. They are located by what they point AT instead — the
#: targets are the same data, so mapping the first few and searching for that
#: sequence lands on the same table in the other release. (name, offset,
#: entries used as the search pattern, entries in the whole table.)
POINTER_TABLES = (
    ("script master table", 0x6299A0, 16, 370),
    ("battle message table", 0x4C8660, 16, 193),
    ("battle slot labels", 0x655410, 4, 4),
)


def find_pointer_table(source: bytes, target: bytes, mapping, at: int,
                       probe: int, count: int) -> int | None:
    """Where a table of pointers sits in the other release.

    Builds what the first ``probe`` entries MUST read as over there — each
    target mapped through the alignment — and looks for that byte sequence.
    A table whose pattern turns up twice, or not at all, is reported rather
    than guessed at.
    """
    from navi.rom import BASE

    pattern = bytearray()
    for i in range(probe):
        word = int.from_bytes(source[at + 4 * i:at + 4 * i + 4], "little")
        if not BASE <= word < BASE + len(source):
            return None
        where = mapping.at(word - BASE)
        if where is None:
            return None
        pattern += (where + BASE).to_bytes(4, "little")
    first = target.find(bytes(pattern))
    if first < 0 or target.find(bytes(pattern), first + 1) >= 0:
        return None
    return first


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    config = Config.load()
    source = Rom.load(config.resolve_rom())
    target = Rom.load(Path(argv[0]).expanduser())
    if source.release.name != "Kuwagata":
        print(f"The source dump must be Kuwagata, not {source.release.name}: "
              "every offset in this project is written against it.")
        return 2
    if target.release.name == source.release.name:
        print("Both dumps are the same release.")
        return 2

    print(f"aligning {source.release.name} with {target.release.name}…")
    mapping = align.compute(bytes(source.data), bytes(target.data),
                            source.release.name, target.release.name)
    covered = mapping.covered()
    print(f"  {len(mapping.runs)} runs covering {covered} of {len(source)} "
          f"bytes ({100 * covered / len(source):.2f}%)")

    ok = True
    for name, offset in ANCHORS:
        where = mapping.at(offset)
        if where is None:
            print(f"  MISSING  {name} ({offset:#08x}) is in no run")
            ok = False
            continue
        print(f"  {name:24s} {offset:#08x} -> {where:#08x}")

    tables: dict[str, list[int]] = {}
    for name, offset, probe, count in POINTER_TABLES:
        where = find_pointer_table(bytes(source.data), bytes(target.data),
                                   mapping, offset, probe, count)
        if where is None:
            print(f"  MISSING  {name} ({offset:#08x}): no unique match")
            ok = False
            continue
        tables[name] = [offset, where, 4 * count]
        print(f"  {name:24s} {offset:#08x} -> {where:#08x}  (pointer table)")

    out = ROOT / "data" / f"offsets-{target.release.name.lower()}.json"
    body = {
        "comment": (
            "Where each stretch of the Kuwagata release sits in the "
            f"{target.release.name} one. Generated by tools/align.py from two "
            "dumps; offsets and lengths only, never bytes. See navi/align.py."),
        "from": source.release.name,
        "to": target.release.name,
        "sha1": {source.release.name: source.sha1, target.release.name: target.sha1},
        "tables": tables,
        "runs": [list(run) for run in mapping.runs],
    }
    out.write_text(json.dumps(body, indent=0, separators=(",", ":")) + "\n",
                   encoding="utf-8")
    print(f"\nwrote {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB)")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
